'use client';

import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import { useEffect } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Firebase Studio App',
//   description: 'Generated by Firebase Studio',
// };

const notes = ['♪', '♫', '♬', '♭', '♮', '♯'];

function createNotes() {
  const movingNotes = document.querySelector('.moving-notes');
  if (!movingNotes) return;

  for (let i = 0; i < 20; i++) {
    const note = document.createElement('span');
    note.classList.add('note');
    note.textContent = notes[Math.floor(Math.random() * notes.length)];

    const randomX = Math.random() * 100; // Random value between 0 and 100
    const randomRotate = Math.random() * 360; // Random value between 0 and 360
    const randomDuration = Math.random() * 5 + 5; // Random value between 5 and 10

    note.style.setProperty('--random-x', `${randomX}vw`);
    note.style.setProperty('--random-rotate', `${randomRotate}deg`);
    note.style.animationDuration = `${randomDuration}s`;

    movingNotes.appendChild(note);
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    createNotes();
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="moving-notes"></div>
        {children}
      </body>
    </html>
  );
}


